name: Build and Test Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t simple-nginx .

    - name: Run container and test
      run: |
        docker run -d -p 8080:80 --name web simple-nginx
        sleep 5
        curl http://localhost:8080
        docker stop web
        docker rm web
